# netlify.toml
[build]
  command = "nuxi build"
  publish = ".output/public"
  functions = ".output/server/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
